
trigger:
- main

pool:
  name: secureagent

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: echo 'Hello world'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "This is for task groups"'

